table Medidas
	lineageTag: 3a787086-ebf7-4970-8543-da8b93c1388d

	measure Faturamento = SUM(fPedidos[faturamento])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 41a4287a-5077-4821-af1d-b97cc090d814

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Custos = SUM(fPedidos[custo])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: a86ecb01-eb44-4f2f-be73-fc8f8ddf412d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Margem Bruta R$' = [Faturamento] - [Custos]
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 7e664a06-3e4f-4970-a23b-7d138d00f145

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Margem Bruta %' = DIVIDE([Margem Bruta R$], [Faturamento])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6fd5e50a-87b4-4744-827b-f8fd35d79317

	measure 'Total Pedidos' = DISTINCTCOUNT(fPedidos[idpedido])
		formatString: 0
		lineageTag: 8d8f60da-f994-461a-852a-51d923837208

	measure 'Ticket Médio' = DIVIDE([Faturamento], [Total Pedidos])
		lineageTag: 78e1bb6f-63b9-4287-a9be-90bf2306a13f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qtd Vendida' = SUM(fPedidos[qtd])
		formatString: 0
		lineageTag: 8d0498c0-daab-44ca-a29e-db933c328156

	measure 'LY Faturamento' = ```
			
			
			CALCULATE([Faturamento], 
			SAMEPERIODLASTYEAR(dCalendario[Data])
			)
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: cb802503-89ad-4681-8049-8b930151d149

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'LY Custos' = ```
			
			
			CALCULATE([Custos], 
			SAMEPERIODLASTYEAR(dCalendario[Data])
			)
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: cbd119ab-87e3-4570-8b5b-3d39bf07f7f8

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'LY Margem Bruta R$' = ```
			
			
			CALCULATE([Margem Bruta R$], 
			SAMEPERIODLASTYEAR(dCalendario[Data])
			)
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 325f810b-7440-4a9b-afea-84dc9adcd102

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'LY Margem Bruta %' = ```
			
			
			CALCULATE([Margem Bruta %], 
			SAMEPERIODLASTYEAR(dCalendario[Data])
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e519eafd-9585-4630-ba7a-bc8b28fb43c5

	measure 'LY Total Pedidos' = ```
			
			
			CALCULATE([Total Pedidos], 
			SAMEPERIODLASTYEAR(dCalendario[Data])
			)
			```
		formatString: 0
		lineageTag: 35c12a3e-5675-4639-96a3-a25b09b4e0e7

	measure 'LY Ticket Médio' = ```
			
			
			CALCULATE([Ticket Médio], 
			SAMEPERIODLASTYEAR(dCalendario[Data])
			)
			```
		lineageTag: da0a1262-6672-4b66-a7e8-6dd4c9d1bb53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LY Qtd vendida' = ```
			
			
			CALCULATE([Qtd Vendida], 
			SAMEPERIODLASTYEAR(dCalendario[Data])
			)
			```
		formatString: 0
		lineageTag: 8414e23b-646c-4673-a962-a346bdb867c1

	measure 'YoY Faturamento' =
			
			
			DIVIDE([Faturamento] - [LY Faturamento], [LY Faturamento])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 933dda09-2417-4d42-8b87-33cb0668c13e

	measure 'YoY Custos' =
			
			
			DIVIDE([Custos] - [LY Custos], [LY Custos])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cdb142f4-9e5a-4ff8-956c-c505b3903ea4

	measure 'YoY Margem R$' =
			
			
			DIVIDE([Margem Bruta R$] - [LY Margem Bruta R$], [LY Margem Bruta R$])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a7e95d5b-86ce-46a6-81bd-d140447b4061

	measure 'YoY Margem %' =
			
			
			DIVIDE([Margem Bruta %] - [LY Margem Bruta %], [LY Margem Bruta %])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 316b9ee3-116e-42b0-8b9c-2f2f3c896a9b

	measure 'YoY Ticket Médio' =
			
			
			DIVIDE([Ticket Médio] - [LY Ticket Médio], [LY Ticket Médio])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 92bea586-a8b4-4ecc-b518-4027b48ce48c

	measure 'YoY Total Pedidos' =
			
			
			DIVIDE([Total Pedidos] - [LY Total Pedidos], [LY Total Pedidos])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2a704634-2ddf-4afc-b7fb-2380441d802e

	measure 'vs Ano Anterior' = "vs. " &COALESCE(SELECTEDVALUE(dCalendario[Ano]) -1 &":", "-")
		lineageTag: 7d08e180-46a5-43ae-b720-17cf74d57cd0

	measure 'Média Pedidos por Dia' =
			
			
			DIVIDE([Total Pedidos], DISTINCTCOUNT(fPedidos[data]))
		lineageTag: 336d69f1-9392-4bdd-b701-348889800ea8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Preço Unitário Médio' =
			
			
			DIVIDE([Faturamento], [Qtd Vendida])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 96d3010d-066c-42a0-807d-b0e6e79a0013

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Custo Unitário' = ```
			
			
			DIVIDE([Custos], [Qtd Vendida])
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: dc5d6885-f416-40ed-81bf-e21e0d60e6d8

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Preço min recomendado' =
			
			
			DIVIDE(- [Custo Unitário], '% Margem Segurança'[Valor % Margem Segurança] - 1)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 46fc597b-e2f1-473f-b453-68838ee8d90a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Var Preço' = DIVIDE([Preço Unitário Médio] - [Preço min recomendado], [Preço min recomendado])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1444043f-469b-47d5-bb36-d4443903f8e6

	column Value
		isHidden
		formatString: 0
		lineageTag: c1761ffe-8b77-47a2-bfd5-2a153739f4af
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition Medidas = calculated
		mode: import
		source = {1}

	annotation PBI_Id = 925c2fe0a65b42f99a0bf08aff8910b0

